### ISSUE TITLE
External links to open in new tab rather than navigating away from current page

### ISSUE THREAD

**Issue by scottwebster** [scottwebster/scottwebster.github.io#8]

**Comment by kenners** [comment]
This is a [poor design practice](http://www.smashingmagazine.com/2008/07/01/should-links-open-in-new-windows): users should always be in control of the interface they are interacting with.

It's better to allow the user to decide whether to open in a new tab (simple middle-click or alt-click) rather than force behaviour.

The only principle exception to this behaviour is when linking to a non-html document e.g. PDF.

**Comment by scottwebster** [comment]
That is just someone’s opinion…surely it’s better to keep the person on my site rather than them ending up on mountain training and finding it more interesting so forgetting to navigate back to my site!

Scott Webster
E-mail:  scott_webster@ymail.com
Mob:  07775 664 642
Web:  www.scottwebster.co.uk http://www.scottwebster.co.uk/

**Comment by kenners** [comment]
> surely it’s better to keep the person on my site rather than them ending up on mountain training and finding it more interesting so forgetting to navigate back to my site!

That would suggest a problem with the content of your site, rather than with navigation ;)

With regard to it being 'just an opinion' – it's a consensus opinion: [Smashing Magazine](http://www.smashingmagazine.com) is pretty well regarded in the web design community, and this view is likewise [echoed by A List Apart](http://alistapart.com/article/designing-for-easy-interaction#section12). 

Very few sites open links in new tabs by default.

Essentially, automagically opening links in new tabs:
- Damages accessibility: it breaks the Back button, as each tab has a separate browser history.
- Impairs usability on mobile devices: navigating between tabs is harder on mobile browsers.
- Denies users a choice

I'd strongly recommend against implementing this.
